language: node_js
node_js:
  - "node"
script:
  -
deploy:
  provider: firebase
  token:
    secure: "ViPuE1oUoQ7MoCjROk+vYS6y8SgBxcdDV/Ji+sRqeVxwXHqYi62SbjW0BFYeGc5SO3EPmFeNulvk0X2tgV597EusWmsVFs/TvW8/RppSvMCYVOxiM6ITuZRoEuY0Cqcd+QJaASp9cyItdUe3HPalJuTOUL7YO9LImV1Kiv/jHceW8maIGa3Ijz0XbRHb5EKgi7yvNGN1rgXUtFwv6muZInmMisMqkWIRm9cjC7/tKOXb9YJODFCnf+gdQRUvtJ2cs0aJ6xQgpUCfHZLbx7pDLYM3t4vB9CsKrnJ7AeG6a5wNeyt2wxiv6VFV5EBe6lLfTmayEdl5xH249JpTdKWG66pN+IfPoeuF93fULLJxBTH3kZ5k1Ky9KA1wCwNPoXz11h71dMi807KZQ6AZq/xpMIolIBVGyTO1vCIEO3IQbV8wU+DelyP1Kn8bRUKsDxMQg9MJ3vybWC7/2fvasEOk7bef1d0YtJhCv65YUbmP7MaLwGVBVLYqdm1jdMubwabrFdjqARdYXiyC0uzwKC5Jb+z+7B52TqmvZG45qfNvWQtQ1y9lzHlZ8ork2p9K6/VDF1ibxsjaHiOaZSTGFM/Pqh0IIU4Bloe8qjEJXiFsqnNsIrVVOvEsPCF92QgzARRC3Uu4/AXq1dH8LbzJkdq08qN0bt3rk+EEZAbzggbiSe0="