language: node_js
node_js:
  -"5.11"

branches:
  only:
    -master

script:
    — echo "Deploy!!"
 
install:
    — npm install -g firebase-tools

after_success:
    -firebase deploy --token=${FIREBASE_API_TOKEN}