language: node_js

node_js:
 — "7"
 
 branches:
  only:
    -master
    
script:
 — echo "Deploy!!"
 
install:
 — npm install -g firebase-tools
 
after_success:
 — firebase deploy — project my-portfolio-page-fab67  - token $FIREBASE_TOKEN.
