language: node_js
node_js:
  - "node"
script:
  -
deploy:
  provider: firebase
  token:
    secure: eyVMr29tx5x39jqPBpgXM2Xzv1zCeUk8OESnShmv0Smvagh6/b+hICgKRHlneNHSUVtzT5NoqyEo28MiRzHVKBItIzNypOjColhX6H9VgAHr6InZri+G6loJFtwvrMdqD67/Y9YzBsK5jjbNI1pvpFqEH/BtOX7ZnpMLx7VurOnG+1gaofIZI9KsKZqItOKavJu9cwuq4RG1PhoDRSQ+iaew5939bPOuVUoIUr95NPAnxKkGndmr9Qoo5qTw7qYaqKHIjvlfAR3B26lVWCT2qbEo2vCmL4SjSadxBxU9ye/wNvE7sYbfl9A9DVtCUeftcrZXkfSKjqPtndN53vMIJm3/fkq0Z/DnLNa5Mqv0SzBqEpCE3qyODx6lOD9fGM6qxdQ1GC2lhR1lgYN4k5Od2Dj5netLzH6hHwDwXtkQzDhB29B0c8Ob+dDgKcHjv27Fo2NIHfzPzbo1BlbjZ/QgvRUVrtFfqSDr6rqhxp0/dC9bYQPYyqspxK+v/Y1d9CRKO6Qi+riEji1MFiO1VOpZ7sT83djueOiHegYkeBguBHaeTppXhu5W0//EHzlLrUEc0xKXLRjmKwTYsId0kZHLgX0B2rRBlMqGebzMHYAF20oTRVsPmEDTPUjxQzeLu9wdpFjqJMKeBC47qr0FkokTSAU9a9mdvIih0QuiPXIVdwM=
project: my-portfolio-page-fab67